export const DEFAULT_MAX_MONTHLY_EARNINGS = 603;
export const DEFAULT_MIN_HOURLY_WAGE = 14.6;
export const DEFAULT_LANGUAGE = 'de';

export const MIN_SHIFTS_FOR_ROLLING_AVG = 1;
export const MAX_SHIFTS_FOR_ROLLING_AVG = 8;
